"""Site metinleri (tr, en) ve iki dilde ortak parçalar.

İlkeler (kurucu kararları): yapılamayanı vaat etme; rakip kıyası, müşteri logosu ya da uydurma
referans yok; marka ibaresi yalnız "Claude ile çalışır" / "Works with Claude"; örnek sayılar
"Örnek veri" etiketiyle ve örnek şirketin sentetik dosyalarından.
"""

from __future__ import annotations


def _simge(yol: str) -> str:
    return (
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" '
        f'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{yol}</svg>'
    )


ORTAK: dict[str, str] = {
    "eposta": "kerem@pasdevs.com",
    "kurucu_ad": "Şamil Kerem Yapar",
    "ik_fire": _simge('<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>'),
    "ik_stok": _simge('<path d="m3 7 9-4 9 4-9 4-9-4Z"/><path d="M3 7v10l9 4 9-4V7M12 11v10"/>'),
    "ik_satinalma": _simge('<path d="M6 6h15l-1.5 9h-12z"/><path d="M6 6 5 3H2"/><circle cx="9" cy="20" r="1.4"/><circle cx="18" cy="20" r="1.4"/>'),
    "ik_bakim": _simge('<path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.5 2.5-2.5-.5-.5-2.5z"/>'),
    "ik_kalite": _simge('<path d="M12 3 5 6v6c0 4.5 3 7.5 7 9 4-1.5 7-4.5 7-9V6z"/><path d="m9 12 2 2 4-4"/>'),
    "ik_satis": _simge('<path d="M3 17 9 11l4 4 8-8"/><path d="M15 7h6v6"/>'),
    "ik_masraf": _simge('<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/>'),
    "ik_izin": _simge('<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4M16 2v4M3 10h18"/>'),
    "ik_uret": _simge('<path d="m12 3 1.9 4.6L18.5 9l-4.6 1.9L12 15.5l-1.9-4.6L5.5 9l4.6-1.4z"/><path d="M19 15l.8 2 2 .8-2 .8-.8 2-.8-2-2-.8 2-.8z"/>'),
    "ik_sunucu": _simge('<rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/><path d="M7 6.5h.01M7 17.5h.01"/>'),
    "ik_anahtar": _simge('<circle cx="8" cy="15" r="4"/><path d="m10.8 12.2 8.2-8.2M17 6l2 2M14 9l2 2"/>'),
    "ik_kayit": _simge('<path d="M8 3h8l4 4v14H4V3z"/><path d="M8 11h8M8 15h8M8 7h4"/>'),
    "ik_maske": _simge('<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"/><path d="M4 20 20 4"/>'),
    "ik_birim": _simge('<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="17" width="6" height="5" rx="1"/><rect x="16" y="17" width="6" height="5" rx="1"/><path d="M12 7v5M5 17v-3h14v3"/>'),
    "ik_onay": _simge('<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>'),
}

TR: dict[str, str] = {
    "dil": "tr",
    "diger_dil": "en",
    "diger_dil_ad": "English",
    "baslik": "PAS — Verinizden uygulamaya",
    "aciklama": "PAS, şirketinizin Excel, CSV ve e-Fatura verisini doğru ve eksiksiz aktarır; her birim için panolara, formlara ve uygulamalara dönüştürür. Kendi bilgisayarınızda ya da sunucunuzda çalışır.",
    "atla": "İçeriğe geç",
    "menu_etiket": "Ana menü",
    "menu_aktarim": "Aktarım",
    "menu_nasil": "Nasıl çalışır",
    "menu_uygulamalar": "Uygulamalar",
    "menu_yz": "Yapay zekâ",
    "menu_guvenlik": "Güvenlik",
    "iletisim_kisa": "İletişim",
    "h1_1": "Verinizden uygulamaya.",
    "h1_2": "Tek yerde.",
    "acilis_giris": "Sektörünüz ve büyüklüğünüz ne olursa olsun, Excel, CSV ve e-Fatura verileriniz doğru ve eksiksiz aktarılır; satıştan insan kaynaklarına her birim kendi panolarıyla, formlarıyla ve uygulamalarıyla çalışır.",
    "gorusme": "Görüşme isteyin",
    "nasil_bag": "Nasıl çalışır",
    "pencere_adres": "pas · Örnek A.Ş.",
    "yan_genel": "Genel",
    "yan_ana": "Ana sayfa",
    "yan_sor": "Veriye sor",
    "yan_uygulamalar": "Uygulamalar",
    "yan_b1": "Satış",
    "yan_b2": "Satın alma",
    "yan_b3": "İnsan kaynakları",
    "yan_b4": "Üretim",
    "yan_yonetim": "Yönetim",
    "yan_kaynaklar": "Veri kaynakları",
    "pano_baslik": "Satış · Son 3 hafta",
    "ornek_veri": "Örnek veri",
    "kpi_1": "Sipariş",
    "kpi_2": "Satış tutarı",
    "kpi_2_deger": "₺400.950",
    "kpi_3": "Satın alma talebi",
    "grafik_baslik": "Günlük satış tutarı",
    "grafik_not": "Son 10 iş günü",
    "gunler": "<span>Pe</span><span>Cu</span><span>Pt</span><span>Sa</span><span>Ça</span><span>Pe</span><span>Cu</span><span>Pt</span><span>Sa</span><span>Ça</span>",
    "aktarim_ust": "Aktarım güvencesi",
    "aktarim_h2": "Her satırın hesabı verilir.",
    "aktarim_giris": "PAS dosyanızı yüklemeden önce okur ve size gösterir: kaç satır alınacak, hangisi neden atlanacak ya da alınmayacak, sayı sütunlarının toplamı dosyadakiyle tutuyor mu. Hiçbir satır sessizce kaybolmaz.",
    "d_okunan": "Dosyadaki satır",
    "d_okunan_not": "Aylık Excel raporu",
    "d_alinan": "Alınan",
    "d_alinan_not": "Veri satırı",
    "d_atlanan": "Atlanan",
    "d_atlanan_not": "Ara ve genel toplamlar",
    "d_reddedilen": "Alınmayan",
    "d_reddedilen_not": "Nedenleriyle listelenir",
    "mutabakat": "Tutar toplamı · dosya: 929.524 · yüklenen: 929.524",
    "aktarim_dipnot": "Örnek veri: ara ve genel toplam satırları olan aylık bir Excel raporu.",
    "oz1_b": "Dört biçim",
    "oz1_p": ".xlsx ve eski .xls, Türkçe karakterli ve ondalık virgüllü CSV, e-Fatura ve e-Arşiv XML.",
    "oz2_b": "Değerler korunur",
    "oz2_p": "Baştaki sıfırlar, hesap kodları, birimli hücreler ve Türkçe tarihler olduğu gibi kalır.",
    "oz3_b": "Geri alınabilir",
    "oz3_p": "Son yüklemeyi tek tıkla geri alın; önceki veri yerine döner.",
    "oz4_b": "Raporlanır",
    "oz4_p": "Alınmayan satırları nedenleriyle birlikte Excel olarak indirebilirsiniz.",
    "nasil_etiket": "Nasıl çalışır",
    "a1_b": "Getirin.",
    "a1_p": "Excel, CSV ve e-Fatura dosyalarınızı yükleyin. PAS sütunları kendisi tanır; ön izlemeyi onayladığınızda veriyi kaydeder.",
    "a2_b": "Kurun ya da üretin.",
    "a2_p": "Hazır uygulamaları tek tıkla birimlerinize kurun. Farklı bir ihtiyacınız varsa tarif edin; PAS pano, ekran ya da uygulama taslağını hazırlasın.",
    "a3_b": "Herkes kendi işini görsün.",
    "a3_p": "Her birim yalnız kendi ekranlarını, formlarını ve raporlarını görür. Yetkiler birim bazında verilir; kimin neyi değiştirdiği kaydedilir.",
    "p1_baslik": "Veri kaynakları",
    "p1_xlsx_ad": "Aylik_Rapor_Eylul.xlsx",
    "p1_csv_ad": "Satis_Ekim.csv",
    "p1_xls_ad": "Stok_Sayimi_2019.xls",
    "p1_xml_ad": "e-Fatura_Ekim.zip",
    "p1_xlsx": "44 satır alındı · 6 toplam satırı atlandı",
    "p1_csv": "Windows-1254 · noktalı virgül · ondalık virgül",
    "p1_xls": "Baştaki sıfırlar korundu · gizli satır bildirildi",
    "p1_xml": "6 satış, 2 alış faturası · tutarlar mutabık",
    "p2_baslik": "Uygulamalar",
    "p2_b1": "Satış birimi",
    "p2_b2": "Finans birimi",
    "p2_b3": "İnsan kaynakları",
    "p2_kurulu": "Kurulu",
    "p2_kur": "Kur",
    "p2_yeni_b": "Müşteri ziyaret formu",
    "p2_yeni": "Tarifinizden taslak",
    "p2_uret": "Üret",
    "p3_baslik": "Birimler",
    "p3_1": "Siparişler ve faturalar",
    "p3_3": "İzin ve masraf",
    "p3_4": "İş emirleri ve fire",
    "uyg_ust": "Hazır uygulamalar",
    "uyg_h2": "İlk günden çalışır.",
    "uyg_giris": "Satın almadan izne, depodan üretime en sık ihtiyaç duyulan uygulamalar hazır gelir: birime kurulur, formu ve listesi hemen kullanılır. Sektörünüze ve işinize özel olanları kendiniz üretirsiniz.",
    "u1_b": "Üretim ve fire",
    "u1_p": "Hat, vardiya ve ürün bazında üretim ve fire.",
    "u2_b": "Stok sayımı",
    "u2_p": "Depo ve malzeme bazında sayım kayıtları.",
    "u3_b": "Satın alma talebi",
    "u3_p": "Birimlerden gelen talepler ve tutarları.",
    "u4_b": "Bakım ve arıza",
    "u4_p": "Makine arızaları ve duruş süreleri.",
    "u5_b": "Kalite kontrol",
    "u5_p": "Parti bazında kontrol ve hata türleri.",
    "u6_b": "Satış siparişi",
    "u6_p": "Müşteriler, ürünler ve teslim tarihleri.",
    "u7_b": "Masraf",
    "u7_p": "Çalışan masrafları ve açıklamaları.",
    "u8_b": "İzin talebi",
    "u8_p": "İzin türleri, günler ve tarihler.",
    "yz_ust": "Yapay zekâ",
    "yz_h2_1": "Yapay zekâ hazırlar.",
    "yz_h2_2": "Karar sizde kalır.",
    "yz_giris": "Sorunuzu yazın, cevap kaynağıyla birlikte gelsin. Pano ya da uygulama isteyin, taslağı hazırlansın. Hiçbir şey onayınız olmadan yayına çıkmaz.",
    "yz1_b": "Verinize sorun",
    "yz1_p": "“Geçen ay en çok satış yaptığımız müşteri kim?” gibi soruları günlük dille sorun; cevap hangi veriden geldiğini gösterir.",
    "yz2_b": "Taslak ve denetim",
    "yz2_p": "Pano, ekran ve uygulama taslaklarını bir model hazırlar, ikinci bir model ayrıca denetler; yayından önce siz onaylarsınız.",
    "yz3_b": "Anahtar ve bütçe sizin",
    "yz3_p": "Kendi Anthropic hesabınızla çalışır; aylık harcama sınırını siz belirlersiniz. Anahtar girmezseniz PAS yapay zekâ olmadan da çalışır.",
    "claude": "Claude ile çalışır",
    "gv_ust": "Güvenlik",
    "gv_h2": "Veriniz sizde kalır.",
    "gv_giris": "Kimin neyi göreceğine ve hangi verinin dışarı çıkacağına siz karar verirsiniz; her değişiklik kayıt altındadır.",
    "g1_b": "Sizin bilgisayarınızda",
    "g1_p": "Kendi bilgisayarınızda ya da sunucunuzda çalışır; iş verileriniz orada kalır.",
    "g2_b": "Passkey ile giriş",
    "g2_p": "Parola ve passkey desteklenir; yönetici işlemleri passkey ile yeniden doğrulanır.",
    "g3_b": "Denetim kaydı",
    "g3_p": "Önemli işlemler zincirli denetim kaydına yazılır; kayıt sonradan değiştirilirse fark edilir.",
    "g4_b": "Maskeleme",
    "g4_p": "Yapay zekâya gönderilen kişisel veriler maskelenir; yurt dışına aktarım kaydı otomatik tutulur.",
    "g5_b": "Birim bazında yetki",
    "g5_p": "Her çalışan yalnız kendi biriminin ekranlarını ve verisini görür.",
    "g6_b": "Onaylı kayıt",
    "g6_p": "Veri kaydeden işlemler, tanımladığınız onay kurallarından geçer.",
    "kap_h2": "PAS'ı şirketinizde görelim.",
    "kap_giris": "Üç adımda, birlikte.",
    "menu_ozellikler": "Özellikler",
    "menu_ac": "Menüyü aç",
    "sema_baslik": "Veri nerede durur, nereye gider?",
    "sema_calisan_b": "Çalışanlar",
    "sema_calisan_p": "Şirket ağındaki her bilgisayardan, tarayıcıyla",
    "sema_ok_ic": "şirket içi",
    "sema_sunucu_b": "Şirketinizin bilgisayarı ya da sunucusu",
    "sema_c2": "Veri tabanı",
    "sema_c3": "Giriş ve yetki",
    "sema_c4": "Denetim kaydı",
    "sema_sunucu_not": "İş verileri burada kalır.",
    "sema_ok_dis": "yalnız maskeli veri · sizin anahtarınız · aylık sınır",
    "sema_claude_p": "İsteğe bağlı; anahtar girmezseniz kullanılmaz",
    "oz_h2": "Teknik özellikler.",
    "t1_b": "Veri kaynakları",
    "t1_p": ".xlsx ve eski .xls; CSV (UTF-8 ya da Windows-1254, virgül ya da noktalı virgül ayraçlı, ondalık virgüllü); e-Fatura ve e-Arşiv XML.",
    "t2_b": "Aktarım",
    "t2_p": "Yüklemeden önce ön izleme; satır satır hesap (alınan, atlanan, alınmayan ve nedeni); tutar mutabakatı; son yüklemeyi geri alma; alınmayan satırlar için Excel raporu.",
    "t3_b": "Uygulamalar",
    "t3_p": "Satış siparişi, satın alma talebi, masraf, izin talebi, stok sayımı, üretim ve fire, bakım ve arıza, kalite kontrol; tarifinizden pano, ekran ve uygulama taslağı.",
    "t4_b": "Yapay zekâ",
    "t4_p": "Claude (Anthropic), kendi anahtarınızla; aylık harcama sınırı; kaynağıyla cevap; taslağı bir model hazırlar, ikinci bir model denetler, siz onaylarsınız. PAS anahtarsız da çalışır.",
    "t5_b": "Erişim",
    "t5_p": "Tarayıcıyla, şirket ağındaki her bilgisayardan.",
    "t6_b": "Giriş ve yetki",
    "t6_p": "Parola ve passkey; yönetici işlemlerinde passkey ile yeniden doğrulama; birim bazında yetki.",
    "t7_b": "Kayıt ve gizlilik",
    "t7_p": "Zincirli denetim kaydı; yapay zekâya gönderilen kişisel veriler maskelenir; yurt dışına aktarım kaydı otomatik tutulur.",
    "t8_b": "Kurulum ve dil",
    "t8_p": "Şirketinizin kendi Windows bilgisayarı ya da sunucusu; Türkçe ve İngilizce arayüz.",
    "s1_b": "Tanışalım",
    "s1_p": "Kısa bir görüşmede işinizi, birimlerinizi ve verinizi konuşuruz.",
    "s2_b": "Size gelelim",
    "s2_p": "Aynı ziyarette PAS'ı örnek şirketle gösterir, bilgisayarınıza ya da sunucunuza kurarız.",
    "s3_b": "Birlikte aktaralım",
    "s3_p": "İlk aktarımı birlikte yapar, toplamların tuttuğunu yerinde kontrol ederiz.",
    "kopyala": "E-postayı kopyala",
    "kopyalandi": "E-posta adresi kopyalandı",
    "alt_tanim": "Verinizden uygulamaya. Tek yerde.",
    "alt_bolumler": "Bölümler",
    "alt_iletisim": "İletişim",
    "cerez": "Bu site çerez kullanmaz ve ziyaretçi verisi toplamaz.",
    "hk_ust": "Hakkımızda",
    "hk_baslik": "Hakkımızda — PAS",
    "hk_aciklama": "PAS'ı Temmuz 2026'dan beri İstanbul'da geliştiriyoruz. Kurucu ve geliştirici: Şamil Kerem Yapar.",
    "hk_giris": "PAS'ı Temmuz 2026'dan beri İstanbul'da geliştiriyoruz. Hedefimiz basit: şirketin bütün verisi tek yerde dursun, her birim yeni ihtiyacını yapay zekâyla kendisi karşılasın.",
    "hk_bas_b": "Başlangıç",
    "hk_bas_p": "Temmuz 2026",
    "hk_yer_b": "Konum",
    "hk_yer_p": "İstanbul, Türkiye",
    "hk_asama_b": "Aşama",
    "hk_asama_p": "Ürün hazır; son kontrolleri yapıp ilk müşteri kurulumuna hazırlanıyoruz.",
    "hk_gel_b": "Geliştiren",
    "hk_gel_p": "Şamil Kerem Yapar, Claude Code",
    "hk_rol": "Kurucu ve geliştirici",
    "hk_bio": "Yıldız Teknik Üniversitesi İstatistik Bölümü öğrencisi.",
}

EN: dict[str, str] = {
    "dil": "en",
    "diger_dil": "tr",
    "diger_dil_ad": "Türkçe",
    "baslik": "PAS — From your data to your apps",
    "aciklama": "PAS imports your company's Excel, CSV and e-invoice data accurately and completely, and turns it into dashboards, forms and apps for every department. It runs on your own computer or server.",
    "atla": "Skip to content",
    "menu_etiket": "Main menu",
    "menu_aktarim": "Import",
    "menu_nasil": "How it works",
    "menu_uygulamalar": "Apps",
    "menu_yz": "AI",
    "menu_guvenlik": "Security",
    "iletisim_kisa": "Contact",
    "h1_1": "From your data to your apps.",
    "h1_2": "In one place.",
    "acilis_giris": "Whatever your industry and size, your Excel, CSV and e-invoice data is imported accurately and completely, and every department, from sales to human resources, works with its own dashboards, forms and apps.",
    "gorusme": "Request a meeting",
    "nasil_bag": "How it works",
    "pencere_adres": "pas · Sample Co.",
    "yan_genel": "General",
    "yan_ana": "Home",
    "yan_sor": "Ask your data",
    "yan_uygulamalar": "Apps",
    "yan_b1": "Sales",
    "yan_b2": "Purchasing",
    "yan_b3": "Human resources",
    "yan_b4": "Production",
    "yan_yonetim": "Administration",
    "yan_kaynaklar": "Data sources",
    "pano_baslik": "Sales · Last 3 weeks",
    "ornek_veri": "Sample data",
    "kpi_1": "Orders",
    "kpi_2": "Sales",
    "kpi_2_deger": "TRY 400,950",
    "kpi_3": "Purchase requests",
    "grafik_baslik": "Daily sales",
    "grafik_not": "Last 10 working days",
    "gunler": "<span>Th</span><span>Fr</span><span>Mo</span><span>Tu</span><span>We</span><span>Th</span><span>Fr</span><span>Mo</span><span>Tu</span><span>We</span>",
    "aktarim_ust": "Import assurance",
    "aktarim_h2": "Every row is accounted for.",
    "aktarim_giris": "Before loading, PAS reads your file and shows you how many rows will be imported, which will be skipped or left out and why, and whether numeric column totals match the file. No row is ever lost silently.",
    "d_okunan": "Rows in file",
    "d_okunan_not": "Monthly Excel report",
    "d_alinan": "Imported",
    "d_alinan_not": "Data rows",
    "d_atlanan": "Skipped",
    "d_atlanan_not": "Subtotals and grand total",
    "d_reddedilen": "Left out",
    "d_reddedilen_not": "Listed with reasons",
    "mutabakat": "Amount total · file: 929,524 · loaded: 929,524",
    "aktarim_dipnot": "Sample data: a monthly Excel report with subtotal and grand total rows.",
    "oz1_b": "Four formats",
    "oz1_p": ".xlsx and legacy .xls, CSV with Turkish characters and decimal commas, Turkish e-invoice and e-archive XML.",
    "oz2_b": "Values preserved",
    "oz2_p": "Leading zeros, account codes, cells with units and Turkish dates stay as they are.",
    "oz3_b": "Reversible",
    "oz3_p": "Undo the last load in one click; the previous data comes back.",
    "oz4_b": "Reported",
    "oz4_p": "Download the rows left out as Excel, with their reasons.",
    "nasil_etiket": "How it works",
    "a1_b": "Bring it in.",
    "a1_p": "Upload your Excel, CSV and e-invoice files. PAS recognizes the columns itself and saves the data once you approve the preview.",
    "a2_b": "Install or generate.",
    "a2_p": "Install ready-made apps into a department in one click. Need something else? Describe it and PAS drafts the dashboard, screen or app.",
    "a3_b": "Everyone sees their own work.",
    "a3_p": "Each department sees only its own screens, forms and reports. Permissions are per department, and every change is recorded.",
    "p1_baslik": "Data sources",
    "p1_xlsx_ad": "Monthly_Report_September.xlsx",
    "p1_csv_ad": "Sales_October.csv",
    "p1_xls_ad": "Stock_Count_2019.xls",
    "p1_xml_ad": "e-Invoice_October.zip",
    "p1_xlsx": "44 rows imported · 6 total rows skipped",
    "p1_csv": "Windows-1254 · semicolon · decimal comma",
    "p1_xls": "Leading zeros kept · hidden row reported",
    "p1_xml": "6 sales, 2 purchase invoices · amounts reconciled",
    "p2_baslik": "Apps",
    "p2_b1": "Sales",
    "p2_b2": "Finance",
    "p2_b3": "Human resources",
    "p2_kurulu": "Installed",
    "p2_kur": "Install",
    "p2_yeni_b": "Customer visit form",
    "p2_yeni": "Drafted from your description",
    "p2_uret": "Generate",
    "p3_baslik": "Departments",
    "p3_1": "Orders and invoices",
    "p3_3": "Leave and expenses",
    "p3_4": "Work orders and scrap",
    "uyg_ust": "Ready-made apps",
    "uyg_h2": "Working from day one.",
    "uyg_giris": "The most commonly needed apps come ready, from purchasing to leave requests and from the warehouse to production: install them into a department and their forms and lists work right away. You build the ones specific to your industry and business yourself.",
    "u1_b": "Production and scrap",
    "u1_p": "Output and scrap by line, shift and product.",
    "u2_b": "Stock count",
    "u2_p": "Count records by warehouse and material.",
    "u3_b": "Purchase request",
    "u3_p": "Requests from departments and their amounts.",
    "u4_b": "Maintenance and faults",
    "u4_p": "Machine faults and downtime.",
    "u5_b": "Quality control",
    "u5_p": "Inspections and defect types by batch.",
    "u6_b": "Sales order",
    "u6_p": "Customers, products and delivery dates.",
    "u7_b": "Expenses",
    "u7_p": "Employee expenses and notes.",
    "u8_b": "Leave request",
    "u8_p": "Leave types, days and dates.",
    "yz_ust": "AI",
    "yz_h2_1": "AI drafts.",
    "yz_h2_2": "You decide.",
    "yz_giris": "Ask a question and get an answer with its source. Ask for a dashboard or an app and get a draft. Nothing is published without your approval.",
    "yz1_b": "Ask your data",
    "yz1_p": "Ask in plain language, like “Which customer did we sell the most to last month?”; the answer shows which data it came from.",
    "yz2_b": "Draft and review",
    "yz2_p": "One model drafts the dashboard, screen or app and a second model reviews it separately; you approve before it is published.",
    "yz3_b": "Your key, your budget",
    "yz3_p": "It runs on your own Anthropic account, and you set the monthly spending limit. Without a key, PAS works without AI.",
    "claude": "Works with Claude",
    "gv_ust": "Security",
    "gv_h2": "Your data stays with you.",
    "gv_giris": "You decide who sees what and which data leaves your company; every change is on record.",
    "g1_b": "On your computer",
    "g1_p": "Runs on your own computer or server; your business data stays there.",
    "g2_b": "Passkey sign-in",
    "g2_p": "Password and passkey are supported; administrator actions are re-verified with a passkey.",
    "g3_b": "Audit log",
    "g3_p": "Important actions are written to a tamper-evident audit log.",
    "g4_b": "Masking",
    "g4_p": "Personal data sent to AI is masked; a cross-border transfer record is kept automatically.",
    "g5_b": "Per-department access",
    "g5_p": "Each employee sees only their department's screens and data.",
    "g6_b": "Approved changes",
    "g6_p": "Actions that save data go through the approval rules you define.",
    "kap_h2": "Let's see PAS at work in your company.",
    "kap_giris": "Three steps, together.",
    "menu_ozellikler": "Specs",
    "menu_ac": "Open menu",
    "sema_baslik": "Where does the data stay, and where does it go?",
    "sema_calisan_b": "Employees",
    "sema_calisan_p": "From any computer on your company network, in the browser",
    "sema_ok_ic": "in-house",
    "sema_sunucu_b": "Your company's computer or server",
    "sema_c2": "Database",
    "sema_c3": "Sign-in and access",
    "sema_c4": "Audit log",
    "sema_sunucu_not": "Business data stays here.",
    "sema_ok_dis": "masked data only · your key · monthly limit",
    "sema_claude_p": "Optional; not used without a key",
    "oz_h2": "Tech specs.",
    "t1_b": "Data sources",
    "t1_p": ".xlsx and legacy .xls; CSV (UTF-8 or Windows-1254, comma- or semicolon-separated, decimal comma); Turkish e-invoice and e-archive XML.",
    "t2_b": "Import",
    "t2_p": "Preview before loading; row-by-row accounting (imported, skipped, left out and why); amount reconciliation; undo the last load; Excel report of rows left out.",
    "t3_b": "Apps",
    "t3_p": "Sales order, purchase request, expenses, leave request, stock count, production and scrap, maintenance and faults, quality control; dashboard, screen and app drafts from your description.",
    "t4_b": "AI",
    "t4_p": "Claude (Anthropic) with your own key; monthly spending limit; answers with sources; one model drafts, a second model reviews and you approve. PAS also works without a key.",
    "t5_b": "Access",
    "t5_p": "In the browser, from any computer on your company network.",
    "t6_b": "Sign-in and access",
    "t6_p": "Password and passkey; passkey re-verification for administrator actions; per-department access.",
    "t7_b": "Logging and privacy",
    "t7_p": "Tamper-evident audit log; personal data sent to AI is masked; a cross-border transfer record is kept automatically.",
    "t8_b": "Installation and language",
    "t8_p": "Your company's own Windows computer or server; Turkish and English interface.",
    "s1_b": "Let's talk",
    "s1_p": "In a short call we talk about your business, your departments and your data.",
    "s2_b": "We come to you",
    "s2_p": "In the same visit we show PAS with a sample company and install it on your computer or server.",
    "s3_b": "Import together",
    "s3_p": "We do the first import together and check on site that the totals match.",
    "kopyala": "Copy email",
    "kopyalandi": "Email address copied",
    "alt_tanim": "From your data to your apps. In one place.",
    "alt_bolumler": "Sections",
    "alt_iletisim": "Contact",
    "cerez": "This site uses no cookies and collects no visitor data.",
    "hk_ust": "About",
    "hk_baslik": "About — PAS",
    "hk_aciklama": "We have been building PAS in Istanbul since July 2026. Founder and developer: Şamil Kerem Yapar.",
    "hk_giris": "We have been building PAS in Istanbul since July 2026. Our goal is simple: all of a company's data in one place, and every department meeting its new needs itself, with AI.",
    "hk_bas_b": "Started",
    "hk_bas_p": "July 2026",
    "hk_yer_b": "Location",
    "hk_yer_p": "Istanbul, Türkiye",
    "hk_asama_b": "Stage",
    "hk_asama_p": "The product is ready; we are running final checks and preparing our first customer installation.",
    "hk_gel_b": "Built by",
    "hk_gel_p": "Şamil Kerem Yapar, Claude Code",
    "hk_rol": "Founder and developer",
    "hk_bio": "Statistics student at Yıldız Technical University.",
}

METINLER: dict[str, dict[str, str]] = {"tr": TR, "en": EN}
