"""Site metinleri (tr, en) ve iki dilde ortak parçalar.

İlkeler (kurucu kararları): yapılamayanı vaat etme; rakip kıyası, müşteri logosu ya da uydurma
referans yok; marka ibaresi yalnız "Claude ile çalışır" / "Works with Claude"; örnek sayılar
"Örnek veri" etiketiyle ve örnek şirketin sentetik dosyalarından.
"""

from __future__ import annotations


def _simge(yol: str) -> str:
    return (
        '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" '
        f'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{yol}</svg>'
    )


ORTAK: dict[str, str] = {
    "eposta": "kerem@pasdevs.com",
    "ik_fire": _simge('<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>'),
    "ik_stok": _simge('<path d="m3 7 9-4 9 4-9 4-9-4Z"/><path d="M3 7v10l9 4 9-4V7M12 11v10"/>'),
    "ik_satinalma": _simge('<path d="M6 6h15l-1.5 9h-12z"/><path d="M6 6 5 3H2"/><circle cx="9" cy="20" r="1.4"/><circle cx="18" cy="20" r="1.4"/>'),
    "ik_bakim": _simge('<path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L3 18l3 3 6.3-6.3a4 4 0 0 0 5.4-5.4l-2.5 2.5-2.5-.5-.5-2.5z"/>'),
    "ik_kalite": _simge('<path d="M12 3 5 6v6c0 4.5 3 7.5 7 9 4-1.5 7-4.5 7-9V6z"/><path d="m9 12 2 2 4-4"/>'),
    "ik_satis": _simge('<path d="M3 17 9 11l4 4 8-8"/><path d="M15 7h6v6"/>'),
    "ik_masraf": _simge('<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18M7 15h4"/>'),
    "ik_izin": _simge('<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4M16 2v4M3 10h18"/>'),
    "ik_uret": _simge('<path d="m12 3 1.9 4.6L18.5 9l-4.6 1.9L12 15.5l-1.9-4.6L5.5 9l4.6-1.4z"/><path d="M19 15l.8 2 2 .8-2 .8-.8 2-.8-2-2-.8 2-.8z"/>'),
    "ik_sunucu": _simge('<rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/><path d="M7 6.5h.01M7 17.5h.01"/>'),
    "ik_anahtar": _simge('<circle cx="8" cy="15" r="4"/><path d="m10.8 12.2 8.2-8.2M17 6l2 2M14 9l2 2"/>'),
    "ik_kayit": _simge('<path d="M8 3h8l4 4v14H4V3z"/><path d="M8 11h8M8 15h8M8 7h4"/>'),
    "ik_maske": _simge('<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"/><path d="M4 20 20 4"/>'),
    "ik_birim": _simge('<rect x="9" y="2" width="6" height="5" rx="1"/><rect x="2" y="17" width="6" height="5" rx="1"/><rect x="16" y="17" width="6" height="5" rx="1"/><path d="M12 7v5M5 17v-3h14v3"/>'),
    "ik_onay": _simge('<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>'),
}

TR: dict[str, str] = {
    "dil": "tr",
    "yol": "",
    "kok": "",
    "kok_bag": "/",
    "diger_dil": "en",
    "diger_dil_bag": "/en/",
    "diger_dil_ad": "English",
    "baslik": "PAS — Verinizden uygulamaya",
    "aciklama": "PAS, şirketinizin Excel, CSV ve e-Fatura verisini doğru ve eksiksiz aktarır; panolara, formlara ve uygulamalara dönüştürür. Kendi bilgisayarınızda ya da sunucunuzda çalışır.",
    "atla": "İçeriğe geç",
    "menu_etiket": "Ana menü",
    "menu_aktarim": "Aktarım",
    "menu_nasil": "Nasıl çalışır",
    "menu_uygulamalar": "Uygulamalar",
    "menu_yz": "Yapay zekâ",
    "menu_guvenlik": "Güvenlik",
    "iletisim_kisa": "İletişim",
    "h1_1": "Verinizden uygulamaya.",
    "h1_2": "Tek yerde.",
    "acilis_giris": "Excel'iniz, CSV'leriniz ve e-Faturalarınız doğru ve eksiksiz aktarılır; şirketinizin kendi panolarına, formlarına ve uygulamalarına dönüşür.",
    "gorusme": "Görüşme isteyin",
    "nasil_bag": "Nasıl çalışır",
    "pencere_adres": "pas · Örnek Makina",
    "yan_genel": "Genel",
    "yan_ana": "Ana sayfa",
    "yan_sor": "Veriye sor",
    "yan_uygulamalar": "Uygulamalar",
    "yan_uretim": "Üretim",
    "yan_bakim": "Bakım",
    "yan_kalite": "Kalite",
    "yan_satis": "Satış",
    "yan_yonetim": "Yönetim",
    "yan_kaynaklar": "Veri kaynakları",
    "pano_baslik": "Üretim · Eylül",
    "ornek_veri": "Örnek veri",
    "kpi_uretilen": "Üretilen",
    "kpi_fire": "Fire oranı",
    "kpi_durus": "Duruş",
    "saat": "sa",
    "grafik_baslik": "Günlük fire",
    "grafik_not": "Perşembeler yüksek",
    "gunler": "<span>Pt</span><span>Sa</span><span>Ça</span><span>Pe</span><span>Cu</span><span>Pt</span><span>Sa</span><span>Pe</span><span>Cu</span><span>Pt</span>",
    "aktarim_ust": "Aktarım güvencesi",
    "aktarim_h2": "Her satırın hesabı verilir.",
    "aktarim_giris": "PAS dosyanızı yüklemeden önce okur ve size gösterir: kaç satır alındı, hangisi neden atlandı ya da alınmadı, sayı sütunlarının toplamı dosyadakiyle tutuyor mu. Sessiz kayıp yok.",
    "d_okunan": "Dosyadaki satır",
    "d_okunan_not": "Eylül üretim raporu",
    "d_alinan": "Alınan",
    "d_alinan_not": "Veri satırı",
    "d_atlanan": "Atlanan",
    "d_atlanan_not": "Ara ve genel toplam",
    "d_reddedilen": "Alınmayan",
    "d_reddedilen_not": "Nedeniyle listelenir",
    "mutabakat": "Tutar toplamı: dosyada 929.524 · yüklenen 929.524",
    "aktarim_dipnot": "Örnek veri: Örnek Makina'nın Eylül üretim raporu.",
    "oz1_b": "Dört biçim",
    "oz1_p": ".xlsx ve eski .xls, Türkçe karakterli ve ondalık virgüllü CSV, e-Fatura ve e-Arşiv XML.",
    "oz2_b": "Değer korunur",
    "oz2_p": "Baştaki sıfır, hesap kodu, birimli hücre ve Türkçe tarih olduğu gibi kalır.",
    "oz3_b": "Geri alınabilir",
    "oz3_p": "Son yüklemeyi tek tıkla geri alın; önceki veri yerine döner.",
    "oz4_b": "Raporlanır",
    "oz4_p": "Alınmayan satırlar nedenleriyle Excel olarak indirilir.",
    "nasil_etiket": "Nasıl çalışır",
    "a1_b": "Getirin.",
    "a1_p": "Excel, CSV ve e-Fatura dosyalarınızı yükleyin. PAS sütunları tanır, ön izlemede her satırın hesabını verir; onaylayınca yazar.",
    "a2_b": "Kurun ya da üretin.",
    "a2_p": "Hazır uygulamaları tek tıkla birime kurun. İhtiyacınız farklıysa yazın: PAS pano, ekran ya da uygulama taslağını hazırlasın.",
    "a3_b": "Herkes kendi işini görsün.",
    "a3_p": "Her birim kendi ekranlarını, formlarını ve raporlarını görür. Yetkiler birim birim; kimin neyi değiştirdiği kayıtlı.",
    "p1_baslik": "Veri kaynakları",
    "p1_xlsx": "44 satır alındı · 6 toplam satırı atlandı",
    "p1_csv": "Windows-1254 · noktalı virgül · ondalık virgül",
    "p1_xls": "Baştaki sıfır korundu · gizli satır bildirildi",
    "p1_xml": "6 satış, 2 alış faturası · tutarlar mutabık",
    "p2_baslik": "Uygulamalar",
    "p2_uretim": "Üretim birimi",
    "p2_bakim": "Bakım birimi",
    "p2_kalite": "Kalite birimi",
    "p2_kurulu": "Kurulu",
    "p2_kur": "Kur",
    "p2_yeni_b": "Duruş kaydı formu",
    "p2_yeni": "Tarifinizden taslak",
    "p2_uret": "Üret",
    "p3_baslik": "Birimler",
    "p3_uretim": "Fire, duruş ve iş emirleri",
    "p3_satis": "Siparişler ve faturalar",
    "p3_ik_b": "İnsan kaynakları",
    "p3_ik": "İzin ve masraf",
    "p3_not": "Her birim yalnız kendi verisini görür.",
    "uyg_ust": "Hazır uygulamalar",
    "uyg_h2": "İlk günden çalışır.",
    "uyg_giris": "Sık ihtiyaç duyulan uygulamalar hazır gelir: birime kurulur, formu ve listesi hemen kullanılır. Gerisini kendiniz üretirsiniz.",
    "u1_b": "Üretim ve fire",
    "u1_p": "Hat, vardiya ve ürün bazında üretim ve fire.",
    "u2_b": "Stok sayımı",
    "u2_p": "Depo ve malzeme bazında sayım kayıtları.",
    "u3_b": "Satın alma talebi",
    "u3_p": "Birimlerden gelen talepler ve tutarları.",
    "u4_b": "Bakım ve arıza",
    "u4_p": "Makine arızaları ve duruş süreleri.",
    "u5_b": "Kalite kontrol",
    "u5_p": "Parti bazında kontrol ve hata türleri.",
    "u6_b": "Satış siparişi",
    "u6_p": "Müşteri, ürün ve teslim tarihleri.",
    "u7_b": "Masraf",
    "u7_p": "Çalışan masrafları ve açıklamaları.",
    "u8_b": "İzin talebi",
    "u8_p": "İzin türleri, günler ve tarihler.",
    "yz_ust": "Yapay zekâ",
    "yz_h2_1": "Yapay zekâ çalışır.",
    "yz_h2_2": "Karar sizde kalır.",
    "yz_giris": "Sorunuzu yazın, cevabı kaynağıyla gelsin. Pano ya da uygulama isteyin, taslağı hazırlansın. Hiçbir şey onayınız olmadan yayına çıkmaz.",
    "yz1_b": "Veriye sorun",
    "yz1_p": "“Hat 2'de hangi gün fire yüksek?” gibi soruları doğal dille sorun; cevap hangi veriden geldiğini gösterir.",
    "yz2_b": "Taslak ve denetim",
    "yz2_p": "Pano, ekran ve uygulama taslağını bir model hazırlar, ikinci bir model ayrıca denetler; yayından önce siz onaylarsınız.",
    "yz3_b": "Anahtar ve bütçe sizin",
    "yz3_p": "Kendi Anthropic hesabınızla çalışır, aylık harcama tavanını siz koyarsınız. Anahtar girmezseniz PAS yapay zekâsız da çalışır.",
    "claude": "Claude ile çalışır",
    "gv_ust": "Güvenlik",
    "gv_h2": "Veriniz sizde kalır.",
    "gv_giris": "PAS şirketinizin kendi bilgisayarına ya da sunucusuna kurulur. Kimin neyi gördüğünü ve değiştirdiğini siz belirlersiniz.",
    "g1_b": "Sizin bilgisayarınızda",
    "g1_p": "Kendi bilgisayarınızda ya da sunucunuzda çalışır; iş verisi orada tutulur.",
    "g2_b": "Passkey ile giriş",
    "g2_p": "Parola ve passkey; yönetici işlemlerinde passkey ile yeniden doğrulama.",
    "g3_b": "Denetim kaydı",
    "g3_p": "Önemli işlemler zincirli denetim kaydına yazılır; sonradan yapılan değişiklik fark edilir.",
    "g4_b": "Maskeleme",
    "g4_p": "Yapay zekâya giden kişisel veri maskelenir; yurt dışı aktarım kaydı kendiliğinden tutulur.",
    "g5_b": "Birim bazında yetki",
    "g5_p": "Her çalışan yalnız kendi biriminin ekranlarını ve verisini görür.",
    "g6_b": "Onaylı yazma",
    "g6_p": "Veri kaydeden işlemler tanımladığınız onay kuralından geçer.",
    "kap_h2": "PAS'ı şirketinizde görelim.",
    "kap_giris": "Size gelelim, kendi verinizle gösterelim. Kurulum ve ilk aktarımı birlikte yapar, mutabakatı birlikte kontrol ederiz.",
    "cerez": "Bu site çerez kullanmaz ve ziyaretçi verisi toplamaz.",
}

EN: dict[str, str] = {
    "dil": "en",
    "yol": "en/",
    "kok": "../",
    "kok_bag": "/en/",
    "diger_dil": "tr",
    "diger_dil_bag": "/",
    "diger_dil_ad": "Türkçe",
    "baslik": "PAS — From your data to your apps",
    "aciklama": "PAS imports your company's Excel, CSV and e-invoice data accurately and completely, and turns it into dashboards, forms and apps. It runs on your own computer or server.",
    "atla": "Skip to content",
    "menu_etiket": "Main menu",
    "menu_aktarim": "Import",
    "menu_nasil": "How it works",
    "menu_uygulamalar": "Apps",
    "menu_yz": "AI",
    "menu_guvenlik": "Security",
    "iletisim_kisa": "Contact",
    "h1_1": "From your data to your apps.",
    "h1_2": "In one place.",
    "acilis_giris": "Your spreadsheets, CSV files and e-invoices are imported accurately and completely, and become your company's own dashboards, forms and apps.",
    "gorusme": "Request a meeting",
    "nasil_bag": "How it works",
    "pencere_adres": "pas · Sample Manufacturing",
    "yan_genel": "General",
    "yan_ana": "Home",
    "yan_sor": "Ask your data",
    "yan_uygulamalar": "Apps",
    "yan_uretim": "Production",
    "yan_bakim": "Maintenance",
    "yan_kalite": "Quality",
    "yan_satis": "Sales",
    "yan_yonetim": "Administration",
    "yan_kaynaklar": "Data sources",
    "pano_baslik": "Production · September",
    "ornek_veri": "Sample data",
    "kpi_uretilen": "Produced",
    "kpi_fire": "Scrap rate",
    "kpi_durus": "Downtime",
    "saat": "h",
    "grafik_baslik": "Daily scrap",
    "grafik_not": "Higher on Thursdays",
    "gunler": "<span>Mo</span><span>Tu</span><span>We</span><span>Th</span><span>Fr</span><span>Mo</span><span>Tu</span><span>Th</span><span>Fr</span><span>Mo</span>",
    "aktarim_ust": "Import assurance",
    "aktarim_h2": "Every row is accounted for.",
    "aktarim_giris": "Before loading, PAS reads your file and shows you how many rows were taken, which were skipped or left out and why, and whether numeric column totals match the file. Nothing is lost silently.",
    "d_okunan": "Rows in file",
    "d_okunan_not": "September production report",
    "d_alinan": "Imported",
    "d_alinan_not": "Data rows",
    "d_atlanan": "Skipped",
    "d_atlanan_not": "Subtotals and grand total",
    "d_reddedilen": "Left out",
    "d_reddedilen_not": "Listed with reasons",
    "mutabakat": "Amount total: 929,524 in file · 929,524 loaded",
    "aktarim_dipnot": "Sample data: a sample manufacturer's September production report.",
    "oz1_b": "Four formats",
    "oz1_p": ".xlsx and legacy .xls, CSV with Turkish characters and decimal commas, Turkish e-invoice and e-archive XML.",
    "oz2_b": "Values preserved",
    "oz2_p": "Leading zeros, account codes, cells with units and Turkish dates stay as they are.",
    "oz3_b": "Reversible",
    "oz3_p": "Undo the last load in one click; the previous data comes back.",
    "oz4_b": "Reported",
    "oz4_p": "Rows left out are downloadable as Excel, with reasons.",
    "nasil_etiket": "How it works",
    "a1_b": "Bring it in.",
    "a1_p": "Upload your Excel, CSV and e-invoice files. PAS recognises the columns, accounts for every row in a preview and writes only when you approve.",
    "a2_b": "Install or generate.",
    "a2_p": "Install ready-made apps into a department in one click. Need something else? Describe it and PAS drafts the dashboard, screen or app.",
    "a3_b": "Everyone sees their own work.",
    "a3_p": "Each department sees its own screens, forms and reports. Permissions are per department, and every change is recorded.",
    "p1_baslik": "Data sources",
    "p1_xlsx": "44 rows imported · 6 total rows skipped",
    "p1_csv": "Windows-1254 · semicolon · decimal comma",
    "p1_xls": "Leading zeros kept · hidden row reported",
    "p1_xml": "6 sales, 2 purchase invoices · amounts reconciled",
    "p2_baslik": "Apps",
    "p2_uretim": "Production",
    "p2_bakim": "Maintenance",
    "p2_kalite": "Quality",
    "p2_kurulu": "Installed",
    "p2_kur": "Install",
    "p2_yeni_b": "Downtime log form",
    "p2_yeni": "Drafted from your description",
    "p2_uret": "Generate",
    "p3_baslik": "Departments",
    "p3_uretim": "Scrap, downtime and work orders",
    "p3_satis": "Orders and invoices",
    "p3_ik_b": "Human resources",
    "p3_ik": "Leave and expenses",
    "p3_not": "Each department sees only its own data.",
    "uyg_ust": "Ready-made apps",
    "uyg_h2": "Working from day one.",
    "uyg_giris": "Commonly needed apps come ready: install them into a department and the form and list work right away. You build the rest yourself.",
    "u1_b": "Production and scrap",
    "u1_p": "Output and scrap by line, shift and product.",
    "u2_b": "Stock count",
    "u2_p": "Count records by warehouse and material.",
    "u3_b": "Purchase request",
    "u3_p": "Requests from departments and their amounts.",
    "u4_b": "Maintenance and faults",
    "u4_p": "Machine faults and downtime.",
    "u5_b": "Quality control",
    "u5_p": "Inspections and defect types by batch.",
    "u6_b": "Sales order",
    "u6_p": "Customers, products and delivery dates.",
    "u7_b": "Expenses",
    "u7_p": "Employee expenses and notes.",
    "u8_b": "Leave request",
    "u8_p": "Leave types, days and dates.",
    "yz_ust": "AI",
    "yz_h2_1": "AI does the work.",
    "yz_h2_2": "You keep the decision.",
    "yz_giris": "Ask a question and get an answer with its source. Ask for a dashboard or an app and get a draft. Nothing is published without your approval.",
    "yz1_b": "Ask your data",
    "yz1_p": "Ask in plain language, like “Which day has high scrap on line 2?”; the answer shows which data it came from.",
    "yz2_b": "Draft and review",
    "yz2_p": "One model drafts the dashboard, screen or app and a second model reviews it separately; you approve before it is published.",
    "yz3_b": "Your key, your budget",
    "yz3_p": "It runs on your own Anthropic account and you set the monthly spending cap. Without a key, PAS works without AI.",
    "claude": "Works with Claude",
    "gv_ust": "Security",
    "gv_h2": "Your data stays with you.",
    "gv_giris": "PAS is installed on your company's own computer or server. You decide who sees and changes what.",
    "g1_b": "On your computer",
    "g1_p": "Runs on your own computer or server; business data is kept there.",
    "g2_b": "Passkey sign-in",
    "g2_p": "Password and passkey; administrator actions require passkey re-verification.",
    "g3_b": "Audit log",
    "g3_p": "Important actions are written to a tamper-evident audit log.",
    "g4_b": "Masking",
    "g4_p": "Personal data sent to AI is masked; a cross-border transfer record is kept automatically.",
    "g5_b": "Per-department access",
    "g5_p": "Each employee sees only their department's screens and data.",
    "g6_b": "Approved writes",
    "g6_p": "Actions that save data pass the approval rule you define.",
    "kap_h2": "Let's see PAS in your company.",
    "kap_giris": "We come to you and show it with your own data. We do the installation and first import together and check the reconciliation together.",
    "cerez": "This site uses no cookies and collects no visitor data.",
}

METINLER: dict[str, dict[str, str]] = {"tr": TR, "en": EN}
